name: Local Meetup Tracking/Action Item
description: Use this issue type to track and manage local meetup organization tasks. Avoid using this issue type for tasks expected to be closed within hours.
title: "[<Tracking>/<Action>] Cloud Native Sustainability Week 2024 <Meetup Location>"
labels: ["issue/needs-triage", "board/unassigned"]
projects: ["cncf/10"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to the TAG!
        Please remember that an issue is not the place to ask questions.
        For inquiries, please refer to the README on how to reach us: [Contact](https://github.com/cncf/tag-env-sustainability#contact).
        Thank you! :)
  - id: description
    type: textarea
    attributes:
      label: Description
      description: |
        Please provide the following details:
        * **Location/Region:**
        * **Organizers:**
        * **Sponsors:**
        * **Date:**
        * **Event link:**
    validations:
      required: true
  - id: details
    type: textarea
    attributes:
      label: Details
      description: What are the goals and activities planned for the meetup?
    validations:
      required: true
  - id: todo
    type: textarea
    attributes:
      label: To-Do
      description: What specific actions are needed to organize this meetup?
      value: |
        1. [Local organizer] Review the [Meetup Organizer Guide](https://docs.google.com/document/d/1xfUqxt0EeMhrsg8h5p_cAJ1ZHzWryrIywue53rVRFJw/edit?usp=sharing) for onboarding.
        2. [Local organizer] Check the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/).
        3. [Local organizer] Create a PR to update the Meetup's table on the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/). Example [PR](https://github.com/cncf/tag-env-sustainability/pull/170).
        4. [TAG ENV Lead] Assign lead organizer/co-lead to the issue.
        5. Tag leads & co-leads if assistance is needed.
    validations:
        required: false
  - id: coc
    type: checkboxes
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://www.cncf.io/conduct/).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - id: comments
    type: textarea
    attributes:
      label: Comments
      description: Additional comments or details.
      placeholder: None
    validations:
        required: false
